import { zodResolver } from "@hookform/resolvers/zod";
import { useQueryClient } from "@tanstack/react-query";
import { Check, Clipboard, Download, Edit3, Heart, LoaderCircle, MessageCircleQuestion, Save, Sparkles, WandSparkles } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { PageHeading } from "../components/layout/AppShell";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardTitle } from "../components/ui/card";
import { ApiError, api, download } from "../lib/api";
import type { Prompt } from "../types";

const schema = z.object({ brief: z.string().min(3, "Opisz cel w co najmniej trzech znakach.").max(8000), model_target: z.enum(["chatgpt", "claude", "both"]), level: z.enum(["standard", "professional", "expert"]), category: z.string().min(2) });
type Values = z.infer<typeof schema>;
const categories = [["programming", "Programowanie"], ["marketing", "Marketing"], ["business", "Biznes"], ["copywriting", "Copywriting"], ["seo", "SEO"], ["science", "Nauka"], ["law", "Prawo"], ["medicine", "Medycyna"], ["data_analysis", "Analiza danych"], ["translation", "Tłumaczenia"], ["education", "Edukacja"], ["other", "Inne"]] as const;

export function GeneratorPage() {
  const queryClient = useQueryClient();
  const [prompt, setPrompt] = useState<Prompt | null>(null);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [editing, setEditing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { brief: "", model_target: "chatgpt", level: "professional", category: "programming" } });
  const create = form.handleSubmit(async (values) => { setError(null); try { const next = await api<Prompt>("/prompts", { method: "POST", body: JSON.stringify(values) }); setPrompt(next); setAnswers({}); queryClient.invalidateQueries({ queryKey: ["dashboard"] }); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Nie udało się utworzyć promptu."); } });
  const answer = async () => { if (!prompt) return; setError(null); try { const next = await api<Prompt>(`/prompts/${prompt.id}/answers`, { method: "POST", body: JSON.stringify({ answers }) }); setPrompt(next); queryClient.invalidateQueries({ queryKey: ["dashboard"] }); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Nie udało się zapisać odpowiedzi."); } };
  const update = async (changes: Partial<Prompt>) => { if (!prompt) return; const next = await api<Prompt>(`/prompts/${prompt.id}`, { method: "PATCH", body: JSON.stringify(changes) }); setPrompt(next); queryClient.invalidateQueries({ queryKey: ["dashboard"] }); };
  const copy = async () => { if (!prompt?.content) return; await navigator.clipboard.writeText(prompt.content); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  const allAnswered = prompt?.questions.every((question) => answers[question]?.trim());
  return <><PageHeading eyebrow="Generator promptów" title="Opisz, co chcesz osiągnąć" description="Nie musisz znać idealnego promptu. Zacznij od celu — pomożemy wydobyć kontekst, który zmienia wynik." />
    <div className="grid items-start gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card><CardTitle>Twój zamiar</CardTitle><form onSubmit={create} className="space-y-5"><label><span className="label">Co chcesz osiągnąć?</span><textarea className="input min-h-48 resize-y leading-relaxed" placeholder="Np. Chcę stworzyć aplikację do zarządzania magazynem dla firmy handlowej." {...form.register("brief")} /><span className="mt-1.5 block text-xs text-slate-400">Nie przejmuj się formą. Im bardziej naturalnie opiszesz cel, tym lepiej.</span>{form.formState.errors.brief && <span className="mt-1 text-xs font-bold text-rose-600">{form.formState.errors.brief.message}</span>}</label><div className="grid gap-4 sm:grid-cols-2"><Select label="Model docelowy" {...form.register("model_target")}>{[["chatgpt", "ChatGPT"], ["claude", "Claude"], ["both", "Oba modele"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select label="Poziom promptu" {...form.register("level")}>{[["standard", "Standard"], ["professional", "Profesjonalny"], ["expert", "Ekspercki"]].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></div><Select label="Kategoria" {...form.register("category")}>{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-500/10 dark:text-rose-200">{error}</p>}<Button type="submit" className="w-full py-3" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? <LoaderCircle className="animate-spin" size={17} /> : <WandSparkles size={17} />}Przeanalizuj opis</Button></form></Card>
      {!prompt && <StarterPanel />}{prompt?.status === "needs_clarification" && <Card><div className="flex size-11 items-center justify-center rounded-xl bg-amber-100 text-amber-600 dark:bg-amber-500/15"><MessageCircleQuestion size={22} /></div><h2 className="mt-5 text-xl font-black">Zanim wygenerujemy prompt</h2><p className="mt-2 text-sm leading-relaxed text-slate-500 dark:text-slate-400">Te odpowiedzi pozwolą stworzyć instrukcję, która jest konkretna i użyteczna od pierwszego użycia.</p><div className="mt-6 space-y-4">{prompt.questions.map((question) => <label key={question} className="block"><span className="label">{question}</span><textarea value={answers[question] ?? ""} onChange={(event) => setAnswers({ ...answers, [question]: event.target.value })} className="input min-h-20 resize-y" placeholder="Wpisz odpowiedź…" /></label>)}</div><Button onClick={answer} disabled={!allAnswered} className="mt-6 w-full"><Sparkles size={17} />Wygeneruj kompletny prompt</Button></Card>}{prompt?.status === "generated" && <Result prompt={prompt} editing={editing} setEditing={setEditing} onUpdate={update} onCopy={copy} copied={copied} />}</div></>;
}

function Select({ label, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string; children: React.ReactNode }) { return <label><span className="label">{label}</span><select className="input" {...props}>{children}</select></label>; }

function StarterPanel() { return <Card className="relative overflow-hidden bg-gradient-to-br from-[#17112f] to-[#30226a] text-white dark:border-violet-400/20"><div className="absolute -right-16 -top-16 size-56 rounded-full bg-fuchsia-500/25 blur-3xl" /><Sparkles className="relative text-violet-200" size={28} /><h2 className="relative mt-8 text-3xl font-black tracking-tight">Zamieniamy intuicję w jasną instrukcję.</h2><ol className="relative mt-8 space-y-5 text-sm text-violet-100">{[["1", "Opisujesz cel własnymi słowami."], ["2", "Doprecyzowujemy brakujący kontekst."], ["3", "Otrzymujesz prompt z oceną jakości."]].map(([number, copy]) => <li className="flex items-center gap-4" key={number}><span className="grid size-8 place-items-center rounded-full border border-violet-300/30 font-black">{number}</span>{copy}</li>)}</ol></Card>; }

function Result({ prompt, editing, setEditing, onUpdate, onCopy, copied }: { prompt: Prompt; editing: boolean; setEditing: (value: boolean) => void; onUpdate: (changes: Partial<Prompt>) => Promise<void>; onCopy: () => Promise<void>; copied: boolean }) {
  const [content, setContent] = useState(prompt.content ?? "");
  return <div className="space-y-6"><Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b pb-4"><div><p className="eyebrow">Gotowe do użycia</p><h2 className="mt-1 text-xl font-black">Twój dopracowany prompt</h2></div><div className="flex gap-2"><Badge tone="green">{prompt.quality_score}/100</Badge><Button variant="ghost" className="px-2.5" onClick={() => onUpdate({ is_favorite: !prompt.is_favorite })} aria-label="Ulubiony"><Heart size={18} fill={prompt.is_favorite ? "currentColor" : "none"} className={prompt.is_favorite ? "text-rose-500" : ""} /></Button></div></div><div className="mt-4">{editing ? <textarea value={content} onChange={(event) => setContent(event.target.value)} className="input min-h-[370px] font-mono text-xs leading-relaxed" /> : <pre className="max-h-[410px] overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-5 font-mono text-xs leading-6 text-slate-100">{prompt.content}</pre>}</div><div className="mt-4 flex flex-wrap gap-2">{editing ? <Button onClick={async () => { await onUpdate({ content }); setEditing(false); }}><Save size={16} />Zapisz zmiany</Button> : <Button variant="secondary" onClick={() => setEditing(true)}><Edit3 size={16} />Edytuj</Button>}<Button variant="secondary" onClick={onCopy}>{copied ? <Check size={16} className="text-emerald-500" /> : <Clipboard size={16} />}{copied ? "Skopiowano" : "Kopiuj"}</Button><Button variant="ghost" onClick={() => download(`/prompts/${prompt.id}/export?format=markdown`, "promptforge-prompt.md")}><Download size={16} />Markdown</Button><Button variant="ghost" onClick={() => download(`/prompts/${prompt.id}/export?format=pdf`, "promptforge-prompt.pdf")}><Download size={16} />PDF</Button></div></Card><Analysis prompt={prompt} /></div>;
}

function Analysis({ prompt }: { prompt: Prompt }) { const groups = [["Mocne strony", prompt.analysis.strengths, "emerald"], ["Do dopracowania", prompt.analysis.weaknesses, "amber"], ["Brakujące informacje", prompt.analysis.missing_information, "rose"], ["Sugestie", prompt.analysis.suggestions, "violet"]] as const; return <div className="grid gap-3 sm:grid-cols-2">{groups.map(([title, items, tone]) => <Card key={title} className="p-4"><h3 className={`text-sm font-black ${tone === "emerald" ? "text-emerald-600" : tone === "amber" ? "text-amber-600" : tone === "rose" ? "text-rose-600" : "text-violet-600"}`}>{title}</h3>{items.length ? <ul className="mt-2 space-y-1.5 text-xs leading-relaxed text-slate-500 dark:text-slate-400">{items.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-2 text-xs text-slate-400">Brak krytycznych uwag.</p>}</Card>)}</div>; }
